wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 8
imgsz:
  desc: null
  value: 640
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718037770
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      - 61
      4: 3.11.7
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    visualize:
      curves/Precision-Recall(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: Precision-Recall(B)
            x-axis-title: Recall
            y-axis-title: Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/Precision-Recall(B)_table
                fields: []
      curves/F1-Confidence(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: F1-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: F1
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/F1-Confidence(B)_table
                fields: []
      curves/Precision-Confidence(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: Precision-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/Precision-Confidence(B)_table
                fields: []
      curves/Recall-Confidence(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: Recall-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/Recall-Confidence(B)_table
                fields: []
