wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 8
imgsz:
  desc: null
  value: 640
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718037387
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
